force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <label>Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Holiday__c/fields/HolidayDate__c.field-meta.xml
<CustomField>
    <fullName>HolidayDate__c</fullName>
    <label>Holiday Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holiday__c/fields/HolidayType__c.field-meta.xml
<CustomField>
    <fullName>HolidayType__c</fullName>
    <label>Holiday Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holiday__c/fields/SouthAfricanID__c.field-meta.xml
<CustomField>
    <fullName>SouthAfricanID__c</fullName>
    <label>South African ID</label>
    <referenceTo>SouthAfricanID__c</referenceTo>
    <relationshipLabel>Holidays</relationshipLabel>
    <relationshipName>Holidays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SouthAfricanID__c/SouthAfricanID__c.object-meta.xml
<CustomObject>
    <description>Object to Store All information related to South African Id searches.</description>
    <label>South African ID</label>
    <nameField>
        <displayFormat>SAId-{0000}</displayFormat>
        <label>South African ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>South African IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SouthAfricanID__c/fields/Citizenship__c.field-meta.xml
<CustomField>
    <fullName>Citizenship__c</fullName>
    <description>Citizenship from Id number.</description>
    <label>Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SA citizen</fullName>
            </value>
            <value>
                <fullName>Permanent resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SouthAfricanID__c/fields/DateofBirth__c.field-meta.xml
<CustomField>
    <fullName>DateofBirth__c</fullName>
    <description>Date of Birth from Id number.</description>
    <label>Date of Birth</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SouthAfricanID__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender from Id number</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SouthAfricanID__c/fields/NumberOfQueries__c.field-meta.xml
<CustomField>
    <fullName>NumberOfQueries__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How many times this ID number has been searched on the platform.</description>
    <label>Number of Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SouthAfricanID__c/fields/SouthAfricanIDNumber__c.field-meta.xml
<CustomField>
    <fullName>SouthAfricanIDNumber__c</fullName>
    <externalId>true</externalId>
    <label>South African ID Number</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/cloudSmithsDevAssignmentController.cls
public with sharing class cloudSmithsDevAssignmentController {

    @AuraEnabled
    public static void saIdSearch(String saID) {
        List<SouthAfricanID__c> saIdList = new List<SouthAfricanID__c>();
        SouthAfricanID__c sfId = new SouthAfricanID__c();
        if(!String.isEmpty(saID)){
            saIdList = [SELECT Id, Citizenship__c, Gender__c, DateofBirth__c, NumberOfQueries__c, SouthAfricanIDNumber__c FROM SouthAfricanID__c WHERE SouthAfricanIDNumber__c =: Long.valueOf(saID)];
        }
        if (saIdList.isEmpty()){
            sfId.DateofBirth__c = saID.substring(4,6) +'/'+ saID.substring(2,4) + '/' +saID.substring(0,2);
            System.debug(sfId.DateofBirth__c);
            sfId.Citizenship__c = integer.valueOf(saID.substring(10, 11)) == 0 ? 'SA citizen' : 'Permanent resident';
            System.debug(sfId.Citizenship__c);
            sfId.Gender__c = integer.valueOf(saID.substring(6, 10)) < 5000 ? 'Female' : 'Male';
            System.debug(sfId.Gender__c);
            sfId.SouthAfricanIDNumber__c = Long.valueOf(saID);
            System.debug(sfId.SouthAfricanIDNumber__c);
            sfId.NumberOfQueries__c = 1;
            insert sfId;
        }else{
            saIdList[0].NumberOfQueries__c += 1;
            update saIdList;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<JSON2Apex.Holidays> getHolidays(String saID) {
        List<JSON2Apex.Holidays> holidays;
        Integer currentYear = System.Today().year();
        String year = '';

        if(Integer.valueOf(String.valueOf(currentYear).substring(2,4)) >= Integer.valueOf(saID.substring(0,2))){
            year = '20'+saID.substring(0,2);
        }else{
            year = '19'+saID.substring(0,2);
        }
        system.debug(year);
        holidays = HolidaysCallouts.makeGetCallout(year);
        
        return holidays;
    }
    // My api ea5636fcdf02b64ebbf825f4bc86a56a14b66ac9

    @AuraEnabled
    public static void saveHolidays(List<JSON2Apex.Holidays> holidays, String saID) {
        system.debug('saveHolidays!!!!!');
        List<SouthAfricanID__c> saIdList = new List<SouthAfricanID__c>();
        List<Holiday__c> holidaylist = new List<Holiday__c>();
        if(!String.isEmpty(saID)){
            saIdList = [SELECT Id, Citizenship__c, Gender__c, DateofBirth__c, NumberOfQueries__c, SouthAfricanIDNumber__c FROM SouthAfricanID__c WHERE SouthAfricanIDNumber__c =: Long.valueOf(saID)];
        }
        if (!saIdList.isEmpty()){
            if(!holidays.isEmpty()){
                for(JSON2Apex.Holidays hol : holidays){
                    Holiday__c holiday = new Holiday__c();
                    holiday.Name = hol.name;
                    holiday.Description__c = hol.description;
                    holiday.HolidayDate__c = hol.date_Z.iso;
                    holiday.HolidayType__c = hol.type[0];
                    holiday.SouthAfricanID__c = saIdList[0].Id;
                    holidaylist.add(holiday);
                }
            }
        }
        insert holidaylist;
    }

}